/**********************************/
/* Table Name: 댓글 */
/**********************************/
DROP TABLE REPLY CASCADE CONSTRAINTS;

CREATE TABLE REPLY (
    REPLYNO     NUMBER(10) NOT NULL PRIMARY KEY,
    CONTENTSNO  NUMBER(10) NOT NULL,
    MEMBERNO    NUMBER(6) NOT NULL,
    MNAME       VARCHAR2(30) NOT NULL,
    CONTENT     VARCHAR2(1000) NOT NULL,
    RDATE       DATE NOT NULL,
    FOREIGN KEY (CONTENTSNO) REFERENCES CONTENTS (CONTENTSNO),
    FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
    FOREIGN KEY (MNAME) REFERENCES MEMBER (MNAME)
);

COMMENT ON TABLE REPLY is '댓글';
COMMENT ON COLUMN REPLY.REPLYNO is '댓글번호';
COMMENT ON COLUMN REPLY.CONTENTSNO is '컨텐츠번호';
COMMENT ON COLUMN REPLY.MEMBERNO is '회원 번호';
COMMENT ON COLUMN REPLY.MNAME is '회원 이름';
COMMENT ON COLUMN REPLY.CONTENT is '내용';
COMMENT ON COLUMN REPLY.RDATE is '등록일';

DROP SEQUENCE REPLY_SEQ;

CREATE SEQUENCE REPLY_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;

-- 댓글 등록
INSERT INTO "TEAM6"."REPLY" ("REPLYNO", "CONTENTSNO", "MEMBERNO", "CONTENT", "PASSWD", "RDATE") 
VALUES (1, 6, 5, '테스트', '1234', SYSDATE);

-- 댓글 목록 조회
SELECT "REPLYNO", "CONTENTSNO", "MEMBERNO", "CONTENT", "PASSWD", "RDATE" 
FROM "TEAM6"."REPLY" 
ORDER BY "REPLYNO" ASC;





-- 특정 댓글 조회
SELECT "REPLYNO", "CONTENTSNO", "MEMBERNO", "CONTENT", "PASSWD", "RDATE" 
FROM "TEAM6"."REPLY" 
WHERE "REPLYNO" = 1;

-- 댓글 수정
UPDATE "TEAM6"."REPLY" 
SET "CONTENTSNO" = 456, "MEMBERNO" = 789, "CONTENT" = '수정된 내용', "PASSWD" = '새로운비밀번호', "RDATE" = SYSDATE
WHERE "REPLYNO" = 1;

-- 댓글 삭제
DELETE FROM "TEAM6"."REPLY" WHERE "REPLYNO" = 1;
