/**********************************/
/* Table Name: 숙소 예약 */
/**********************************/
DROP TABLE RESERVATION;

CREATE TABLE RESERVATION(
		ROOMNO                        		NUMBER(5)		 NOT NULL		 PRIMARY KEY,
		MEMBERNO                      		NUMBER(10)		 NOT NULL,
		MNAME                         		VARCHAR2(30)		 NOT NULL,
		CHECKIN_DATE                  		DATE		 NOT NULL,
		CHECKOUT_DATE                 		DATE		 NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (ROOMNO) REFERENCES ROOM (ROOMNO)
);

COMMENT ON TABLE RESERVATION is '숙소 예약';
COMMENT ON COLUMN RESERVATION.ROOMNO is '방 번호';
COMMENT ON COLUMN RESERVATION.MEMBERNO is '회원번호';
COMMENT ON COLUMN RESERVATION.MNAME is '성명';
COMMENT ON COLUMN RESERVATION.CHECKIN_DATE is '체크인 날짜';
COMMENT ON COLUMN RESERVATION.CHECKOUT_DATE is '체크아웃 날짜';

COMMIT;