/**********************************/
/* Table Name: 숙박시설 */
/**********************************/
DROP TABLE ACCOMMODATION;
CREATE TABLE ACCOMMODATION(
		ACCOMMODATIONNO               		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		NAME                          		VARCHAR2(100)		 NOT NULL,
		A_CONTACT                     		VARCHAR2(100)		 NOT NULL,
		ADDRESS                       		VARCHAR2(200)		 NOT NULL,
		DESCRIPTION                   		VARCHAR2(400)		 NULL ,
		RATING                        		NUMBER(2,1)		 NULL 
);

COMMENT ON TABLE ACCOMMODATION is '숙박시설';
COMMENT ON COLUMN ACCOMMODATION.ACCOMMODATIONNO is '숙박시설 번호';
COMMENT ON COLUMN ACCOMMODATION.NAME is '이름';
COMMENT ON COLUMN ACCOMMODATION.A_CONTACT is '연락처';
COMMENT ON COLUMN ACCOMMODATION.ADDRESS is '주소';
COMMENT ON COLUMN ACCOMMODATION.DESCRIPTION is '설명';
COMMENT ON COLUMN ACCOMMODATION.RATING is '평점';

COMMIT;